### ISSUE TITLE
how to correctly pass variant value for `option(int)` as param in array?

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-cli-js#211]
## Given entrypoint
https://github.com/aeternity/fire-editor/blob/master/src/app/contracts/hamster.ts#L67

## Attempts
```sh
marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aex141-nft-collection-example$ aecli -V
4.1.0
marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aex141-nft-collection-example$ aecli contract call sample-wallet --contractSource contracts/CryptoHamster.aes --contractAddress ct_4yziyT427SLvPQVZCKX4zSQvkUy7X1c6W8Vi2SwpGMB2pDCBR --callStatic get_hamster_dna '["abc", None]'
Can't parse contract arguments: Unexpected token N in JSON at position 8
marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aex141-nft-collection-example$ aecli contract call sample-wallet --contractSource contracts/CryptoHamster.aes --contractAddress ct_4yziyT427SLvPQVZCKX4zSQvkUy7X1c6W8Vi2SwpGMB2pDCBR --callStatic get_hamster_dna '["abc", "None"]'
✔ Enter your password … ****
/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/types/FateInt.js:8
        this._value = BigInt(value)
                      ^

SyntaxError: Cannot convert None to a BigInt
    at BigInt (<anonymous>)
    at new FateInt (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/types/FateInt.js:8:23)
    at PrimitiveDataFactory.create (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/DataFactory/PrimitiveDataFactory.js:38:20)
    at ExternalDataFactory.create (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/DataFactory/CompositeDataFactory.js:42:24)
    at ExternalDataFactory.create (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/ExternalDataFactory.js:13:22)
    at /home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/DataFactory/CompositeDataFactory.js:35:50
    at Array.map (<anonymous>)
    at ExternalDataFactory.createMultiple (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/DataFactory/CompositeDataFactory.js:35:35)
    at VariantDataFactory.create (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/DataFactory/VariantDataFactory.js:53:48)
    at ExternalDataFactory.create (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/DataFactory/CompositeDataFactory.js:42:24)
marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aex141-nft-collection-example$ aecli contract call sample-wallet --contractSource contracts/CryptoHamster.aes --contractAddress ct_4yziyT427SLvPQVZCKX4zSQvkUy7X1c6W8Vi2SwpGMB2pDCBR --callStatic get_hamster_dna '["abc", 0n]'
Can't parse contract arguments: Unexpected token n in JSON at position 9
marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aex141-nft-collection-example$ aecli contract call sample-wallet --contractSource contracts/CryptoHamster.aes --contractAddress ct_4yziyT427SLvPQVZCKX4zSQvkUy7X1c6W8Vi2SwpGMB2pDCBR --callStatic get_hamster_dna '["abc", 0]'
✔ Enter your password … ****
file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-sdk/es/contract/aci.mjs:186
    throw new NodeInvocationError(message, transaction);
          ^

NodeInvocationError: Invocation failed: "Expected 1 arguments, got 2"
    at handleCallError (file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-sdk/es/contract/aci.mjs:186:11)
    at Object.instance.call (file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-sdk/es/contract/aci.mjs:350:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.call (file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/bin/actions/contract.mjs:145:22)
    at async Command.parseAsync (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/commander/lib/command.js:917:5)
    at async runProgram (file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/bin/utils/CliError.mjs:10:5)
    at async file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/bin/aecli-contract.mjs:21:1 {
  transaction: 'tx_+G0rAaEBEPr12sU8zc1RmYIbIHuOQvEuiOBpoMuzyH+Omh3tIG4CoQUJCwwmp++69JNblQzx17rRufCdQRKVfwGoEpt/MIBn/gOGpbpmXvgAAACDWMW0hDuaygCSKxGpCJhGKw1hYmOvggABARsAQPIUBQ=='
}
marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aex141-nft-collection-example$ aecli contract call sample-wallet --contractSource contracts/CryptoHamster.aes --contractAddress ct_4yziyT427SLvPQVZCKX4zSQvkUy7X1c6W8Vi2SwpGMB2pDCBR --callStatic get_hamster_dna '["abc"]'
✔ Enter your password … ****
file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-sdk/es/contract/aci.mjs:186
    throw new NodeInvocationError(message, transaction);
          ^

NodeInvocationError: Invocation failed: "Expected 1 arguments, got 2"
    at handleCallError (file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-sdk/es/contract/aci.mjs:186:11)
    at Object.instance.call (file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-sdk/es/contract/aci.mjs:350:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.call (file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/bin/actions/contract.mjs:145:22)
    at async Command.parseAsync (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/commander/lib/command.js:917:5)
    at async runProgram (file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/bin/utils/CliError.mjs:10:5)
    at async file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/bin/aecli-contract.mjs:21:1 {
  transaction: 'tx_+GwrAaEBEPr12sU8zc1RmYIbIHuOQvEuiOBpoMuzyH+Omh3tIG4CoQUJCwwmp++69JNblQzx17rRufCdQRKVfwGoEpt/MIBn/gOGpbW+RzAAAACDWMXIhDuaygCRKxGpCJhGKw1hYmOvggABAD9raHK9'
}
marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aex141-nft-collection-example$ aecli contract call sample-wallet --contractSource contracts/CryptoHamster.aes --contractAddress ct_4yziyT427SLvPQVZCKX4zSQvkUy7X1c6W8Vi2SwpGMB2pDCBR --callStatic get_hamster_dna '["abc", None]'
Can't parse contract arguments: Unexpected token N in JSON at position 8
marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aex141-nft-collection-example$ aecli contract call sample-wallet --contractSource contracts/CryptoHamster.aes --contractAddress ct_4yziyT427SLvPQVZCKX4zSQvkUy7X1c6W8Vi2SwpGMB2pDCBR --callStatic get_hamster_dna '["abc", "None"]'
✔ Enter your password … ****
/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/types/FateInt.js:8
        this._value = BigInt(value)
                      ^

SyntaxError: Cannot convert None to a BigInt
    at BigInt (<anonymous>)
    at new FateInt (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/types/FateInt.js:8:23)
    at PrimitiveDataFactory.create (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/DataFactory/PrimitiveDataFactory.js:38:20)
    at ExternalDataFactory.create (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/DataFactory/CompositeDataFactory.js:42:24)
    at ExternalDataFactory.create (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/ExternalDataFactory.js:13:22)
    at /home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/DataFactory/CompositeDataFactory.js:35:50
    at Array.map (<anonymous>)
    at ExternalDataFactory.createMultiple (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/DataFactory/CompositeDataFactory.js:35:35)
    at VariantDataFactory.create (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/DataFactory/VariantDataFactory.js:53:48)
    at ExternalDataFactory.create (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-calldata/src/DataFactory/CompositeDataFactory.js:42:24)
marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aex141-nft-collection-example$ aecli contract call sample-wallet --contractSource contracts/CryptoHamster.aes --contractAddress ct_4yziyT427SLvPQVZCKX4zSQvkUy7X1c6W8Vi2SwpGMB2pDCBR --callStatic get_hamster_dna '["abc", undefined]'
Can't parse contract arguments: Unexpected token u in JSON at position 8
marc0olo@DESKTOP-B1QLEDL:~/git/aeternity/aex141-nft-collection-example$ aecli contract call sample-wallet --contractSource contracts/CryptoHamster.aes --contractAddress ct_4yziyT427SLvPQVZCKX4zSQvkUy7X1c6W8Vi2SwpGMB2pDCBR --callStatic get_hamster_dna '["abc", 0]'
✔ Enter your password … ****
file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-sdk/es/contract/aci.mjs:186
    throw new NodeInvocationError(message, transaction);
          ^

NodeInvocationError: Invocation failed: "Expected 1 arguments, got 2"
    at handleCallError (file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-sdk/es/contract/aci.mjs:186:11)
    at Object.instance.call (file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/@aeternity/aepp-sdk/es/contract/aci.mjs:350:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.call (file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/bin/actions/contract.mjs:145:22)
    at async Command.parseAsync (/home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/node_modules/commander/lib/command.js:917:5)
    at async runProgram (file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/bin/utils/CliError.mjs:10:5)
    at async file:///home/marc0olo/.nvm/versions/node/v16.16.0/lib/node_modules/@aeternity/aepp-cli/bin/aecli-contract.mjs:21:1 {
  transaction: 'tx_+G0rAaEBEPr12sU8zc1RmYIbIHuOQvEuiOBpoMuzyH+Omh3tIG4CoQUJCwwmp++69JNblQzx17rRufCdQRKVfwGoEpt/MIBn/gOGpbpmXvgAAACDWMW0hDuaygCSKxGpCJhGKw1hYmOvggABARsAQPIUBQ=='
}
```

**Comment by davidyuk** [comment]
> Invocation failed: "Expected 1 arguments, got 2"

This error returned by node's dry-run, so seems that you are using a different code than deployed on chain.

I've redeployed it and it looks fine
```
$ aecli contract call --contractSource ./hamster.aes --contractAddress ct_YQkcQsM4HW56E1M7FZbwcKX2k8C57T4hNo9EVkpMkQaHgrJ42 --callStatic get_hamster_dna '["abc", 4]'
----------------------Call info-----------------------
Contract address ________________________ ct_YQkcQsM4HW56E1M7FZbwcKX2k8C57T4hNo9EVkpMkQaHgrJ42
Gas price _______________________________ 1000000000
Gas used ________________________________ 2127
Return value (encoded) __________________ cb_b6AFycpvHlKpo6VnoeqVIxz+EqBlqcslyumWpij2WRZjrnoMSWo=
Return value (decoded) __________________ 2618097651446293132953519837534926523893588278180327121807849674093874275310

$ aecli contract call --contractSource ./hamster.aes --contractAddress ct_YQkcQsM4HW56E1M7FZbwcKX2k8C57T4hNo9EVkpMkQaHgrJ42 --callStatic get_hamster_dna '["abc", null]'     
----------------------Call info-----------------------
Contract address ________________________ ct_YQkcQsM4HW56E1M7FZbwcKX2k8C57T4hNo9EVkpMkQaHgrJ42
Gas price _______________________________ 1000000000
Gas used ________________________________ 2127
Return value (encoded) __________________ cb_b6AFycpvHlKpo6VnoeqVIxz+EqBlqcslyumWpij2WRZjrnoMSWo=
Return value (decoded) __________________ 2618097651446293132953519837534926523893588278180327121807849674093874275310

$ aecli contract call --contractSource ./hamster.aes --contractAddress ct_YQkcQsM4HW56E1M7FZbwcKX2k8C57T4hNo9EVkpMkQaHgrJ42 --callStatic get_hamster_dna '["abc"]'      
----------------------Call info-----------------------
Contract address ________________________ ct_YQkcQsM4HW56E1M7FZbwcKX2k8C57T4hNo9EVkpMkQaHgrJ42
Gas price _______________________________ 1000000000
Gas used ________________________________ 2127
Return value (encoded) __________________ cb_b6AFycpvHlKpo6VnoeqVIxz+EqBlqcslyumWpij2WRZjrnoMSWo=
Return value (decoded) __________________ 2618097651446293132953519837534926523893588278180327121807849674093874275310

$ aecli contract call --contractSource ./hamster.aes --contractAddress ct_YQkcQsM4HW56E1M7FZbwcKX2k8C57T4hNo9EVkpMkQaHgrJ42 --callStatic get_hamster_dna '["abc", "4"]'
----------------------Call info-----------------------
Contract address ________________________ ct_YQkcQsM4HW56E1M7FZbwcKX2k8C57T4hNo9EVkpMkQaHgrJ42
Gas price _______________________________ 1000000000
Gas used ________________________________ 2127
Return value (encoded) __________________ cb_b6AFycpvHlKpo6VnoeqVIxz+EqBlqcslyumWpij2WRZjrnoMSWo=
Return value (decoded) __________________ 2618097651446293132953519837534926523893588278180327121807849674093874275310
```

So, according to JSON, JS semantings you can pass `option(int)`
- as a plain number (BigInt not supported in JSON) 
- as a string containing number
- `null` as a lack of value (`undefined` not supported in JSON)
- or just omit the value if it is the lat argument

**Comment by marc0olo** [comment]
> This error returned by node's dry-run, so seems that you are using a different code than deployed on chain.

ok yeah, didn't know what exactly has been deployed. still strange the error as it is the same when I pass 1 argument and 2 arguments. I think this is still an issue. not sure where exactly.

when writing I think I know where the problem is in that regards. had an interesting discussion this morning with @loxs.

so I have sourcecode A (or the ACI of it)  which doesn't reflect the state of the deployed contract as you correctly say. so....

> * or just omit the value if it is the lat argument

**this** specific behavior makes the compiler to provide 2 params to the contract call **ALTHOUGH** I only provided 1 param explicitely 🤔 

I think this "omitting" value should not be possible. do you agree? it was incredible confusing to me

**Comment by davidyuk** [comment]
> still strange the error as it is the same when I pass 1 argument and 2 arguments

This is a calldata magic, it is converting `["abc", 0]` to `["abc", 0]`, and `["abc"]` to `["abc", <none>]`, so the node received 2 arguments in both cases.

> this specific behavior makes the compiler to provide 2 params to the contract call

yep

> I think this "omitting" value should not be possible. do you agree?

Nope, it was done by my request to have consistent behaviour when calling sophia methods from js.

Can we fix this by interpreting "Expected 1 arguments, got 2" as "Provided ACI is incompatible with deployed contract" on SDK side?

**Comment by marc0olo** [comment]
> Can we fix this by interpreting "Expected 1 arguments, got 2" as "Provided ACI is incompatible with deployed contract" on SDK side?

if you prefer that we can fix it this way, yes. but current behavior is inacceptable IMO. the proposed error in SDK would help a lot to know what's going on.
